import App from '../components/App';
import './globals.css';
import { Inter } from 'next/font/google';
import {NavBar} from "../components/NavBar";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<App>
					<main className='flex flex-col items-center justify-between p-24'>
					<NavBar/>
					{children}
					</main>
				</App>
			</body>
		</html>
	);
}
